### ISSUE TITLE
127.0.0.1:8500: connect: connection refused

### ISSUE THREAD

**Issue by kakaNo1** [ning1875/dynamic-sharding#4]
![图片](https://user-images.githubusercontent.com/33709305/103965972-da585400-5199-11eb-8182-3781a57e6a8b.png)
```
consul_server:
  # consul api 地址
  addr: localhost:8500
  username:
  password:
  # promethues中consul sd中pgw service name
  register_service_name: pushgateway
# 服务web addr
http_listen_addr: :9292
# pgw信息
pushgateway:
  port: 9091
  servers:
    - 10.0.28.239
    - 10.0.29.24
  ```
